# Generated by Django 3.1 on 2020-08-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20200807_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropLocation',
        ),
    ]
